In [1]:
import pandas as pd

In [2]:
sal=pd.read_csv('Salaries.csv')

In [4]:
sal.head(2)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN

In [5]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [6]:
sal['BasePay'].mean()

66325.4488404877

In [8]:
sal['OvertimePay'].max()

245131.88

In [19]:
sal[sal['EmployeeName']=="JOSEPH DRISCOLL"]['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [22]:
sal[sal['EmployeeName']=="JOSEPH DRISCOLL"]['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [23]:
sal.loc[sal['TotalPayBenefits'].idxmax()]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [25]:
sal.loc[sal['TotalPayBenefits'].argmin()]

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                    0.0
OvertimePay                                0.0
OtherPay                               -618.13
Benefits                                   0.0
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 148653, dtype: object

In [39]:
sal.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status              float64
dtype: object

In [40]:
import numpy as np

In [41]:
# Convert 'BasePay' to numeric, forcing errors to NaN
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')

# Now group by 'Year' and calculate the mean of 'BasePay'
mean_basepay_by_year = sal.groupby('Year')['BasePay'].mean()
print(mean_basepay_by_year)

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [42]:
sal['JobTitle'].nunique()

2159

In [45]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [54]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts()==1)

202

In [55]:
def chief_string(title):
    if "chief" in title.lower().split():
        return True
    else:
        return False

In [59]:
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

477

In [60]:
sal['title_length']=sal['JobTitle'].apply(len)

In [65]:
sal[['TotalPayBenefits','title_length']].corr()

                  TotalPayBenefits  title_length
TotalPayBenefits          1.000000     -0.036878
title_length             -0.036878      1.000000